srv check for open port in a loop

diff --git a/bin/srv b/bin/srv
--- a/bin/srv
+++ b/bin/srv
@@ -1,29 +1,42 @@
 #!/bin/bash
 
+# Configuration
+HOST=localhost
+PORT=8000
+
 # Stop on errors
 set -Eeuo pipefail
 
 # Start server
-# bundle exec jekyll serve --bind localhost 8000 & PID=$!
-python3 -m http.server --bind localhost 8000 & PID=$!
+SERVERCMD="python3 -m http.server --bind ${HOST} ${PORT}"
+echo $SERVERCMD
+$SERVERCMD & PID=$!
 
 # Register handler to kill server on exit
 function cleanup() {
   kill ${PID} || echo "Error killing process ${PID}"
+  exit
 }
 trap cleanup SIGINT SIGQUIT SIGABRT SIGKILL SIGTERM ERR
 
-# FIXME error check for open port or crashed server in a loop
-
-# Make sure server is running
-sleep 1
+# Wait for server to start with a timeout
+for i in  `seq 10` ; do
+  if nc -z ${HOST} ${PORT} &> /dev/null; then
+    break
+  fi
+  sleep 0.2
+done
 if ! kill -0 ${PID} &> /dev/null; then
-  echo "Error: server failed to start"
-  exit 1
+  echo "Error: server process is not running"
+  cleanup
+fi
+if ! nc -z ${HOST} ${PORT} &> /dev/null; then
+  echo "Error: ${HOST}:${PORT} is not open"
+  cleanup
 fi
 
 # Open browser tab
-open http://localhost:8000
+open "http://${HOST}:${PORT}"
 
 # Wait for all processes to exit
 wait
