srv += Jekyll remote theme support

diff --git a/bin/srv b/bin/srv
--- a/bin/srv
+++ b/bin/srv
@@ -8,9 +8,12 @@ PORT=8000
 set -Eeuo pipefail
 
 # Intelligently choose the right server
-if [ -e _config.yml ]; then
-  # Looks like a GitHub pages
+if [ -e _config.yml ] && grep -q '^plugins' _config.yml; then
+  # Jekyll with primer-spec remote them
   SERVERCMD="bundle exec jekyll serve --host ${HOST} --port ${PORT}"
+elif [ -e _config.yml ]; then
+  # Jekyll
+  SERVERCMD="jekyll serve --host ${HOST} --port ${PORT}"
 else
   # Default to HTTP file server
   SERVERCMD="python3 -m http.server --bind ${HOST} ${PORT}"
@@ -18,7 +21,7 @@ fi
 
 # Register handler to kill server on exit
 function cleanup() {
-  kill ${PID} || echo "Error killing process ${PID}"
+  kill -SIGINT ${PID} || echo "Error killing process ${PID}"
 }
 trap cleanup SIGINT SIGQUIT SIGABRT SIGKILL SIGTERM ERR
 
